# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0003_mantencion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='numero_ot',
            field=models.IntegerField(),
        ),

    ]

