# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0005_mantencion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('info', models.TextField(max_length=500)),
            ],
        ),
    ]
