# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0006_informacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
