# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0007_auto_20170312_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='are',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantPlanta.Informacion'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
