# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0008_auto_20170312_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='are',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='informacion',
        ),
    ]
