# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0015_auto_20170313_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='marca',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='informacion',
            name='tension',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
