# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0016_auto_20170313_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='tension',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
