# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0017_auto_20170313_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
    ]
