# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0019_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantPlanta.Planta'),
        ),
    ]
