# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0021_auto_20170324_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='rechazada',
            field=models.BooleanField(default=False),
        ),
    ]
