# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantPlanta', '0022_mantencion_rechazada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(max_length=500)),
                ('fecha', models.DateField()),
                ('realizador', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantPlanta.Mantencion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
