# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0025_auto_20170330_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='fecha_aprec',
            field=models.DateField(blank=True, null=True),
        ),
    ]
