# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantPlanta', '0026_mantencion_fecha_aprec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accion',
            name='mantecion',
        ),
        migrations.DeleteModel(
            name='Accion',
        ),
    ]
